<?php
	require_once('configNomTables.php');

	DEFINE('ANNONCES_HOME_URL', WP_PLUGIN_URL . '/' . ANNONCES_PLUGIN_DIR . '/');
	DEFINE('ANNONCES_INC_PLUGIN_URL', ANNONCES_HOME_URL . 'includes/');
	
	DEFINE('ANNONCES_LIB_PLUGIN_DIR', ANNONCES_INC_PLUGIN_DIR . 'lib/');
	DEFINE('ANNONCES_MODULES_PLUGIN_DIR', ANNONCES_INC_PLUGIN_DIR . 'modules/');
?>